
import database.CourseDatabase;
import database.MySqlConnect;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author S Wadhwani
 */
public class Course extends javax.swing.JPanel {
        Connection conn=null;
        PreparedStatement preparedStatement=null;
        ResultSet rs =null;
        CourseDatabase courseDatabase=null;
        DashboardPanel dashboardPanel=null; 
        
        /**
     * Creates new form Course
     */
    
    public Course() {
        conn=MySqlConnect.connectDB("documentmanagement1");
        initComponents();
        
        //setSize(630, 499);
        AlphaJTextfield obj=new AlphaJTextfield(txtCourseName,lblCheckName);
        courseDatabase = new CourseDatabase();
        CustomJTable.insertInJtable(jtbCourse,"course");
    
        //setVisible(true);
       // updateTableData();
    }
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtCourseName = new javax.swing.JTextField();
        txtAcronym = new javax.swing.JTextField();
        lblCourseName = new javax.swing.JLabel();
        lblAcronym = new javax.swing.JLabel();
        lblCheckName = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbCourse = new javax.swing.JTable();

        setBackground(new java.awt.Color(26, 27, 65));

        jPanel1.setBackground(new java.awt.Color(26, 27, 65));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(247, 212, 136)));
        jPanel1.setForeground(new java.awt.Color(31, 1, 185));

        txtCourseName.setBackground(new java.awt.Color(26, 27, 65));
        txtCourseName.setForeground(new java.awt.Color(247, 212, 136));
        txtCourseName.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(247, 212, 136), 1, true));
        txtCourseName.setCaretColor(new java.awt.Color(255, 255, 255));

        txtAcronym.setBackground(new java.awt.Color(26, 27, 65));
        txtAcronym.setForeground(new java.awt.Color(247, 212, 136));
        txtAcronym.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(247, 212, 136), 1, true));
        txtAcronym.setCaretColor(new java.awt.Color(255, 255, 255));
        txtAcronym.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtAcronymKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAcronymKeyTyped(evt);
            }
        });

        lblCourseName.setBackground(new java.awt.Color(255, 255, 51));
        lblCourseName.setFont(new java.awt.Font("Malgun Gothic Semilight", 1, 14)); // NOI18N
        lblCourseName.setForeground(new java.awt.Color(247, 212, 136));
        lblCourseName.setText("Course name");

        lblAcronym.setBackground(new java.awt.Color(255, 255, 51));
        lblAcronym.setFont(new java.awt.Font("Malgun Gothic Semilight", 1, 14)); // NOI18N
        lblAcronym.setForeground(new java.awt.Color(247, 212, 136));
        lblAcronym.setText("Acronym");

        lblCheckName.setBackground(new java.awt.Color(26, 27, 65));
        lblCheckName.setForeground(new java.awt.Color(26, 27, 65));

        btnAdd.setBackground(new java.awt.Color(26, 27, 65));
        btnAdd.setFont(new java.awt.Font("Malgun Gothic Semilight", 1, 14)); // NOI18N
        btnAdd.setForeground(new java.awt.Color(26, 27, 65));
        btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/yellow.png"))); // NOI18N
        btnAdd.setText("ADD");
        btnAdd.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(247, 212, 136)));
        btnAdd.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAdd.setOpaque(false);
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCourseName)
                    .addComponent(lblAcronym, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(lblCheckName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtAcronym, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCourseName, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(105, 105, 105))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCheckName, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCourseName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCourseName))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAcronym)
                    .addComponent(txtAcronym, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        jtbCourse.setAutoCreateRowSorter(true);
        jtbCourse.setBackground(new java.awt.Color(26, 27, 65));
        jtbCourse.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jtbCourse.setForeground(new java.awt.Color(247, 212, 136));
        jtbCourse.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtbCourse.setEnabled(false);
        jtbCourse.setGridColor(new java.awt.Color(247, 212, 136));
        jtbCourse.setRowHeight(22);
        jScrollPane1.setViewportView(jtbCourse);
        jtbCourse.setShowGrid(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 441, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(107, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtAcronymKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAcronymKeyTyped

        if(!(isBackSpace)){
            if(!(Character.isAlphabetic(evt.getKeyChar()))){
                JOptionPane.showMessageDialog(null, "connot add anything other than field");
                evt.consume();
            }
        }

    }//GEN-LAST:event_txtAcronymKeyTyped

    private void txtAcronymKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAcronymKeyPressed

        isBackSpace=false;
        if(evt.getKeyChar() == evt.VK_BACK_SPACE){
            //  evt.consume();

            isBackSpace = true;
        }
    }//GEN-LAST:event_txtAcronymKeyPressed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        if(lblCheckName.getText().equals("y")){
            if(txtAcronym.getText().equals(""))
            JOptionPane.showMessageDialog(null, "Please insert proper course acronym","LoginSuccessed",JOptionPane.WARNING_MESSAGE);
            else{
                if(courseDatabase.insert(txtCourseName.getText(),txtAcronym.getText())){

                    JOptionPane.showMessageDialog(null, "Record inserted","LoginSuccessed",JOptionPane.INFORMATION_MESSAGE);
                    dashboardPanel=DashBoardMain.getDashboardPanel();
                    dashboardPanel.addCourseInJCBCourse();
                    dashboardPanel.p.addCourseInJCBCourse();
                    dashboardPanel.s.addCourseInJCBCourse();
                    CustomJTable.insertInJtable(jtbCourse,"course");

                }
            }
        }
        else
            JOptionPane.showMessageDialog(null, "Please insert proper course name","Course",JOptionPane.WARNING_MESSAGE);
      //  updateTableData();
    }//GEN-LAST:event_btnAddActionPerformed
    public CourseDatabase getCourseDatabase(){
        return courseDatabase;
    }
                                          

    private void init(){
        JFrame jf=new JFrame();
        //jf.getContentPane().add(new Professor(courseDatabase));
        jf.setVisible(true);
        jf.setSize(430,370);
    }
    //this main is for testing purpose
    public static void main(String args[]){
       new Course().init();
    }
    /*private void updateTableData(){
        try{
            String sql = "SELECT * FROM course";
            preparedStatement = conn.prepareStatement(sql);
            rs=preparedStatement.executeQuery();
           
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"issue : " + e.getMessage());
        }finally{
            try{
                rs.close();
                preparedStatement.close();
            }catch(Exception e){
                JOptionPane.showMessageDialog(null,"issue : " + e.getMessage());
            }
        }
    }*/
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtbCourse;
    private javax.swing.JLabel lblAcronym;
    private javax.swing.JLabel lblCheckName;
    private javax.swing.JLabel lblCourseName;
    private javax.swing.JTextField txtAcronym;
    private javax.swing.JTextField txtCourseName;
    // End of variables declaration//GEN-END:variables
    private boolean isBackSpace ;
    
}
