
import database.ProfessorDatabase;
import database.SubjectDatabase;
import database.DocumentDatabase;
import database.SemesterDatabase;
import database.CourseDatabase;
import database.MySqlConnect;
import java.awt.CardLayout;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author rp wadhwani
 */
public class LoginPanel extends javax.swing.JPanel {

    Connection conn = null;
    ResultSet rs = null;
    PreparedStatement preparedStatement = null;

    Pnl2 pnl2;
    Semester sem;
    Course c;
    Professor p;
    Subject s;
    CourseDatabase courseDatabase;
    SemesterDatabase semesterDatabase;
    ProfessorDatabase professorDatabase;
    SubjectDatabase subjectDatabase;
    DocumentDatabase documentDatabase;
    Pnl1 pnl1;
    CardLayout cl = new CardLayout();
    MainPnl mainPnl;

    /**
     * Creates new form LoginPanel
     */
    public Subject getSubject() {
        return s;
    }

    public LoginPanel(MainPnl mp) {
        initComponents();
        mainPnl = mp;
        pnl1 = mainPnl.getPnl1();
        pnl2 = mainPnl.getPnl2();

        c = new Course();
        sem = new Semester();
        s = new Subject(c.getCourseDatabase(), sem.getSemesterDatabase());

        setSize(800, 510);
        conn = MySqlConnect.connectDB("documentmanagement");
        txtName.setText(PlaceholderConstants.USERNAME);
        txtPassword.setText(PlaceholderConstants.PASSWORD);
        // jp =  Login.getPanel();
        // pack();
        //  getFrame().setResizable(false);
        //this.setResizeable(false);

        txtPassword.setEchoChar((char) 0);
    }

    private void checkFields() {
        if (txtName.getText().equals(PlaceholderConstants.USERNAME) || txtPassword.getText().equals(PlaceholderConstants.PASSWORD)) {
            JOptionPane.showMessageDialog(null, "USername or password is required.");
        } else {
            processLogin();
        }

    }

    private void processLogin() {
        try {
            String sql = "SELECT * FROM login WHERE username = ? AND password=?";
            preparedStatement = conn.prepareStatement(sql);
            preparedStatement.setString(1, txtName.getText());
            preparedStatement.setString(2, txtPassword.getText());
            rs = preparedStatement.executeQuery();
            if (rs.next()) {

                cl = (CardLayout) pnl1.getLayout();

            } else {
                JOptionPane.showMessageDialog(null, "Login UnSuccesfull!", "Login", JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Exception  : " + e, "LoginPAnel", JOptionPane.INFORMATION_MESSAGE);

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblLogin = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        txtName = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        btnLogin1 = new javax.swing.JButton();
        txtFocus = new javax.swing.JTextField();

        setBackground(new java.awt.Color(247, 212, 136));

        jPanel1.setBackground(new java.awt.Color(26, 27, 65));
        jPanel1.setForeground(new java.awt.Color(0, 255, 255));
        jPanel1.setOpaque(true);
        jPanel1.setLayout(null);

        lblLogin.setBackground(new java.awt.Color(255, 255, 51));
        lblLogin.setFont(new java.awt.Font("Calibri", 3, 36)); // NOI18N
        lblLogin.setForeground(new java.awt.Color(255, 255, 255));
        lblLogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Name_100px.png"))); // NOI18N
        jPanel1.add(lblLogin);
        lblLogin.setBounds(70, 60, 116, 100);

        jPanel2.setBackground(new java.awt.Color(26, 27, 65));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(247, 212, 136)));

        txtName.setBackground(new java.awt.Color(26, 27, 65));
        txtName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtName.setForeground(new java.awt.Color(247, 212, 136));
        txtName.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(247, 212, 136)));
        txtName.setCaretColor(new java.awt.Color(255, 255, 255));
        txtName.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtName.setOpaque(true
        );
        txtName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNameFocusLost(evt);
            }
        });
        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtName, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(7, 7, 7))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(20, 170, 235, 52);

        jPanel3.setBackground(new java.awt.Color(26, 27, 65));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(247, 212, 136)));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/key-with-padlock.png"))); // NOI18N

        txtPassword.setBackground(new java.awt.Color(26, 27, 65));
        txtPassword.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtPassword.setForeground(new java.awt.Color(247, 212, 136));
        txtPassword.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtPassword.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(247, 212, 136)));
        txtPassword.setCaretColor(new java.awt.Color(255, 255, 255));
        txtPassword.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtPassword.setEchoChar('*');
        txtPassword.setOpaque(true);
        txtPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPasswordFocusLost(evt);
            }
        });
        txtPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(txtPassword))
                .addContainerGap())
        );

        jPanel1.add(jPanel3);
        jPanel3.setBounds(20, 230, 234, 56);

        btnLogin1.setBackground(new java.awt.Color(0, 51, 51));
        btnLogin1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnLogin1.setForeground(new java.awt.Color(255, 255, 255));
        btnLogin1.setText("LOGIN");
        btnLogin1.setBorder(null);
        btnLogin1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnLogin1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogin1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnLogin1);
        btnLogin1.setBounds(20, 300, 232, 37);

        txtFocus.setBorder(null);
        txtFocus.setCaretColor(new java.awt.Color(29, 74, 95));
        txtFocus.setOpaque(false);
        txtFocus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFocusActionPerformed(evt);
            }
        });
        jPanel1.add(txtFocus);
        txtFocus.setBounds(190, 70, 0, 14);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(65, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNameFocusGained
        // TODO add your handling code here:
        if ((txtName.getText().equals(PlaceholderConstants.USERNAME))) {
            txtName.setText("");
        }
    }//GEN-LAST:event_txtNameFocusGained

    private void txtNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNameFocusLost
        // TODO add your handling code here:
        if ((txtName.getText().equals(""))) {
            txtName.setText(PlaceholderConstants.USERNAME);
        }
    }//GEN-LAST:event_txtNameFocusLost

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
        checkFields();
    }//GEN-LAST:event_txtNameActionPerformed

    private void txtPasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPasswordFocusGained

        if (txtPassword.getText().equals(PlaceholderConstants.PASSWORD)) {

            txtPassword.setText("");
            txtPassword.setEchoChar('*');
        }
    }//GEN-LAST:event_txtPasswordFocusGained

    private void txtPasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPasswordFocusLost
        if ((txtPassword.getText().equals(""))) {
            txtPassword.setEchoChar((char) 0);
            txtPassword.setText(PlaceholderConstants.PASSWORD);

        }
    }//GEN-LAST:event_txtPasswordFocusLost

    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordActionPerformed
        // TODO add your handling code here:
        checkFields();
    }//GEN-LAST:event_txtPasswordActionPerformed

    private void btnLogin1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogin1ActionPerformed
        // TODO add your handling code here:
        checkFields();
    }//GEN-LAST:event_btnLogin1ActionPerformed

    private void txtFocusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFocusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFocusActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblLogin;
    private javax.swing.JTextField txtFocus;
    private javax.swing.JTextField txtName;
    private javax.swing.JPasswordField txtPassword;
    // End of variables declaration//GEN-END:variables
}
