
import java.awt.GridLayout;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author rp wadhwani
 */
public class MainPnl extends javax.swing.JPanel {

    /**
     * Creates new form MainPnl
     */
    Login l;
    Pnl1 pnl1;
    Pnl2 pnl2;
    public MainPnl(Login l) {
        this.l=l;
        pnl1=new Pnl1(this);
        
        
        pnl2=new Pnl2(this);
        initComponents();
        setSize(800,530);
        setLayout(new GridLayout(1, 2, 10, 0));
        add(pnl1);
        add(pnl2);
        pnl1.initLoginPanel();
        setVisible(true);
    }

    public Pnl1 getPnl1(){
        return pnl1;
    }
    public Pnl2 getPnl2(){
        return pnl2;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(0, 255, 255));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
