
import database.MySqlConnect;
import java.awt.CardLayout;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import java.awt.CardLayout;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.PrintStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author rp wadhwani
 */
public class MyLogin extends javax.swing.JPanel {

    /**
     * Creates new form MyLogin
     */
   


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author rp wadhwani
 */

    Connection conn=null;
    ResultSet rs=null;
    PreparedStatement preparedStatement=null;
   
    
    
    
    /**
     * Creates new form LoginPanel
     */
   
   Project p;
    public MyLogin(Project p) {
        initComponents();
        
       this.p=p;
       
        setSize(800,510);
        conn=MySqlConnect.connectDB("documentmanagement");
        txtName.setText(PlaceholderConstants.USERNAME);
        txtPassword.setText(PlaceholderConstants.PASSWORD);
       // jp =  Login.getPanel();
       // pack();
     //  getFrame().setResizable(false);
       //this.setResizeable(false);
      
        txtPassword.setEchoChar((char)0);
    }
     private void checkFields(){
        if(txtName.getText().equals(PlaceholderConstants.USERNAME) || txtPassword.getText().equals(PlaceholderConstants.PASSWORD))
            JOptionPane.showMessageDialog(null,"USername or password is required.");
        else
            processLogin();
            
    }
      private void processLogin(){
        try {
             String sql="SELECT * FROM login WHERE username = ? AND password=?";
            preparedStatement=conn.prepareStatement(sql);
            preparedStatement.setString(1,txtName.getText());
            preparedStatement.setString(2,txtPassword.getText());
            rs=preparedStatement.executeQuery();
            if(rs.next()){
              
               p.dispose();
               DashBoardMain.main(null);
               
               
            }
            else{
                JOptionPane.showMessageDialog(null,"Login UnSuccesfull!","Login",JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"Exception  : " + e,"LoginPAnel",JOptionPane.INFORMATION_MESSAGE);
            
        }
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblLogin = new javax.swing.JLabel();
        btnLogin1 = new javax.swing.JButton();
        txtFocus = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();

        jPanel1.setBackground(new java.awt.Color(247, 212, 136));

        jPanel2.setBackground(new java.awt.Color(26, 27, 65));
        jPanel2.setForeground(new java.awt.Color(0, 255, 255));
        jPanel2.setOpaque(true);
        jPanel2.setLayout(null);

        lblLogin.setBackground(new java.awt.Color(255, 255, 51));
        lblLogin.setFont(new java.awt.Font("Calibri", 3, 36)); // NOI18N
        lblLogin.setForeground(new java.awt.Color(255, 255, 255));
        lblLogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Name_100px.png"))); // NOI18N
        jPanel2.add(lblLogin);
        lblLogin.setBounds(70, 40, 130, 110);

        btnLogin1.setBackground(new java.awt.Color(26, 27, 65));
        btnLogin1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnLogin1.setForeground(new java.awt.Color(26, 27, 65));
        btnLogin1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/yellow.png"))); // NOI18N
        btnLogin1.setText("LOGIN");
        btnLogin1.setBorder(null);
        btnLogin1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnLogin1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogin1ActionPerformed(evt);
            }
        });
        jPanel2.add(btnLogin1);
        btnLogin1.setBounds(90, 320, 100, 30);

        txtFocus.setBorder(null);
        txtFocus.setCaretColor(new java.awt.Color(29, 74, 95));
        txtFocus.setOpaque(false);
        txtFocus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFocusActionPerformed(evt);
            }
        });
        jPanel2.add(txtFocus);
        txtFocus.setBounds(190, 70, 0, 14);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user.png"))); // NOI18N
        jPanel2.add(jLabel1);
        jLabel1.setBounds(22, 160, 40, 50);

        txtName.setBackground(new java.awt.Color(26, 27, 65));
        txtName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtName.setForeground(new java.awt.Color(247, 212, 136));
        txtName.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(247, 212, 136)));
        txtName.setCaretColor(new java.awt.Color(255, 255, 255));
        txtName.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtName.setOpaque(true
        );
        txtName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNameFocusLost(evt);
            }
        });
        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });
        jPanel2.add(txtName);
        txtName.setBounds(70, 170, 170, 30);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/key-with-padlock.png"))); // NOI18N
        jPanel2.add(jLabel3);
        jLabel3.setBounds(22, 220, 40, 50);

        txtPassword.setBackground(new java.awt.Color(26, 27, 65));
        txtPassword.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtPassword.setForeground(new java.awt.Color(247, 212, 136));
        txtPassword.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtPassword.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(247, 212, 136)));
        txtPassword.setCaretColor(new java.awt.Color(255, 255, 255));
        txtPassword.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtPassword.setEchoChar('*');
        txtPassword.setOpaque(true);
        txtPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPasswordFocusLost(evt);
            }
        });
        txtPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordActionPerformed(evt);
            }
        });
        jPanel2.add(txtPassword);
        txtPassword.setBounds(70, 230, 170, 30);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(65, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 401, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 470, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNameFocusGained
        // TODO add your handling code here:
        if((txtName.getText().equals(PlaceholderConstants.USERNAME)))
        txtName.setText("");
    }//GEN-LAST:event_txtNameFocusGained

    private void txtNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNameFocusLost
        // TODO add your handling code here:
        if((txtName.getText().equals(""))){
            txtName.setText(PlaceholderConstants.USERNAME);
        }
    }//GEN-LAST:event_txtNameFocusLost

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
        checkFields();
    }//GEN-LAST:event_txtNameActionPerformed

    private void txtPasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPasswordFocusGained

        if(txtPassword.getText().equals(PlaceholderConstants.PASSWORD))
        {

            txtPassword.setText("");
            txtPassword.setEchoChar('*');
        }
    }//GEN-LAST:event_txtPasswordFocusGained

    private void txtPasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPasswordFocusLost
        if((txtPassword.getText().equals(""))){
            txtPassword.setEchoChar((char)0);
            txtPassword.setText(PlaceholderConstants.PASSWORD);

        }
    }//GEN-LAST:event_txtPasswordFocusLost

    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordActionPerformed

        try {
            // TODO add your handling code here:
/*            System.setOut(new PrintStream(new File("C:\\Users\\rp wadhwani\\Desktop")));
            System.out.print("          HI My\nname is pankaj");*/
        } catch (Exception ex) {
            Logger.getLogger(MyLogin.class.getName()).log(Level.SEVERE, null, ex);
        }
checkFields();
    }//GEN-LAST:event_txtPasswordActionPerformed

    private void btnLogin1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogin1ActionPerformed
        checkFields();
    }//GEN-LAST:event_btnLogin1ActionPerformed

    private void txtFocusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFocusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFocusActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblLogin;
    private javax.swing.JTextField txtFocus;
    private javax.swing.JTextField txtName;
    private javax.swing.JPasswordField txtPassword;
    // End of variables declaration//GEN-END:variables
}
