
import database.ProfessorDatabase;
import database.SubjectDatabase;
import database.SemesterDatabase;
import database.CourseDatabase;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author S Wadhwani
 */
public class Professor extends javax.swing.JPanel {

    /**
     * Creates new form Professor
     */
    CourseDatabase courseDatabase;
    SemesterDatabase semesterDatabase;
    SubjectDatabase subjectDatabase; 
    ProfessorDatabase professorDatabase;
    DashboardPanel dashboardPanel=null;
    private boolean constructor;
    public Professor(CourseDatabase cdb,SemesterDatabase sdb,SubjectDatabase subdb) {
        initComponents();
        AlphaJTextfield pName=new AlphaJTextfield(txtProffesorName, lblCheck);
        courseDatabase=cdb;
        semesterDatabase=sdb;
        subjectDatabase = subdb;
        professorDatabase=new ProfessorDatabase();
        
        constructor=true;
        
        addCourseInJCBCourse();
        addSemInJCBSem();
        addSubjectInListSubject();
        CustomJTable.insertInJtable(jtbProfessor,"professor" );
    }
    public void addSubjectInListSubject(){
        String subjects[];
       
        if(cSelected && semSelected && constructor){
            listSubject.removeAll();
            //subjects=subjectDatabase.getSubjects(jcbCourseName.getItemAt(0),Integer.parseInt((String)jcbSem.getSelectedItem()));
            
            subjects=subjectDatabase.getSubjects((String)jcbCourseName.getSelectedItem(),Integer.parseInt((String)jcbSem.getSelectedItem()));
            for (String subject : subjects) {
                listSubject.setModel( new javax.swing.AbstractListModel<String>(){
                   @Override
                   public int getSize() { return subjects.length; }
                   @Override
                   public String getElementAt(int i) { return subjects[i]; }
               });
            }
        }
    }
    public void addCourseInJCBCourse(){
        jcbCourseName.removeAllItems();
        String courses[]=courseDatabase.getAllCourses();
        for (String course : courses) {
            jcbCourseName.addItem(course);
        }
    }
    public void addSemInJCBSem(){
        jcbSem.removeAllItems();
        int sems[]=semesterDatabase.getSems();
        for(int i=0;i<sems.length;i++){
            jcbSem.addItem(sems[i]+"");
            System.out.println(sems[i]);
        }
    }
    public ProfessorDatabase getProfessorDatabase(){
        return professorDatabase;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        txtProffesorName = new javax.swing.JTextField();
        lblProffesorName = new javax.swing.JLabel();
        lblCourseName = new javax.swing.JLabel();
        jcbCourseName = new javax.swing.JComboBox<>();
        lblSubject = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();
        jcbSem = new javax.swing.JComboBox<>();
        lblSem = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listSubject = new javax.swing.JList<>();
        lblCheck = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtbProfessor = new javax.swing.JTable();

        setBackground(new java.awt.Color(26, 27, 65));

        mainPanel.setBackground(new java.awt.Color(26, 27, 65));
        mainPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(247, 212, 136)));
        mainPanel.setForeground(new java.awt.Color(244, 91, 105));

        txtProffesorName.setBackground(new java.awt.Color(244, 91, 105));
        txtProffesorName.setFont(new java.awt.Font("Malgun Gothic Semilight", 1, 14)); // NOI18N
        txtProffesorName.setForeground(new java.awt.Color(247, 212, 136));
        txtProffesorName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(247, 212, 136)));
        txtProffesorName.setCaretColor(new java.awt.Color(255, 255, 255));
        txtProffesorName.setOpaque(false);

        lblProffesorName.setBackground(new java.awt.Color(0, 0, 0));
        lblProffesorName.setFont(new java.awt.Font("Malgun Gothic Semilight", 1, 14)); // NOI18N
        lblProffesorName.setForeground(new java.awt.Color(247, 212, 136));
        lblProffesorName.setText("Professor Name");

        lblCourseName.setBackground(new java.awt.Color(0, 0, 0));
        lblCourseName.setFont(new java.awt.Font("Malgun Gothic", 1, 14)); // NOI18N
        lblCourseName.setForeground(new java.awt.Color(247, 212, 136));
        lblCourseName.setText("Course Name");

        jcbCourseName.setFont(new java.awt.Font("Malgun Gothic Semilight", 1, 14)); // NOI18N
        jcbCourseName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbCourseNameActionPerformed(evt);
            }
        });

        lblSubject.setBackground(new java.awt.Color(0, 0, 0));
        lblSubject.setFont(new java.awt.Font("Malgun Gothic Semilight", 1, 14)); // NOI18N
        lblSubject.setForeground(new java.awt.Color(247, 212, 136));
        lblSubject.setText("Subject");

        btnAdd.setBackground(new java.awt.Color(0, 0, 0));
        btnAdd.setFont(new java.awt.Font("Malgun Gothic Semilight", 1, 14)); // NOI18N
        btnAdd.setForeground(new java.awt.Color(26, 27, 65));
        btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/yellow.png"))); // NOI18N
        btnAdd.setText(" Add");
        btnAdd.setBorder(null);
        btnAdd.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        jcbSem.setFont(new java.awt.Font("Malgun Gothic", 1, 14)); // NOI18N
        jcbSem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbSemActionPerformed(evt);
            }
        });

        lblSem.setBackground(new java.awt.Color(0, 0, 0));
        lblSem.setFont(new java.awt.Font("Malgun Gothic", 1, 14)); // NOI18N
        lblSem.setForeground(new java.awt.Color(247, 212, 136));
        lblSem.setText("Semester");

        /*
        listSubject.setForeground(new java.awt.Color(244, 91, 105));
        listSubject.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        */
        jScrollPane1.setViewportView(listSubject);

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblSubject, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblCourseName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblProffesorName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblSem, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(39, 39, 39)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jcbSem, 0, 134, Short.MAX_VALUE)
                    .addComponent(txtProffesorName)
                    .addComponent(jcbCourseName, 0, 134, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(31, 31, 31))
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(160, 160, 160)
                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(160, 160, 160))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProffesorName, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtProffesorName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbCourseName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCourseName, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSem)
                    .addComponent(jcbSem, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                        .addGap(24, 24, 24))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(lblSubject)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        lblCheck.setBackground(new java.awt.Color(26, 27, 65));
        lblCheck.setForeground(new java.awt.Color(26, 27, 65));
        lblCheck.setText("jLabel1");

        jtbProfessor.setBackground(new java.awt.Color(26, 27, 65));
        jtbProfessor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jtbProfessor.setForeground(new java.awt.Color(247, 212, 136));
        jtbProfessor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtbProfessor.setEnabled(false);
        jtbProfessor.setGridColor(new java.awt.Color(247, 212, 136));
        jtbProfessor.setRowHeight(22);
        jScrollPane2.setViewportView(jtbProfessor);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblCheck)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 206, Short.MAX_VALUE)
                .addComponent(lblCheck, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jcbCourseNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbCourseNameActionPerformed
       cSelected=true;   
       addSubjectInListSubject();
    }//GEN-LAST:event_jcbCourseNameActionPerformed

    private void jcbSemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbSemActionPerformed
       semSelected=true; 
       addSubjectInListSubject();
    }//GEN-LAST:event_jcbSemActionPerformed
    private boolean checkFields(){
        if(txtProffesorName.getText().equals(null)){
            JOptionPane.showMessageDialog(null,"Enter professor name","Professor", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        else if(jcbCourseName.getSelectedItem()==null){
            JOptionPane.showMessageDialog(null,"Select course name","Professor", JOptionPane.ERROR_MESSAGE);
                return false;
        }
        else if(jcbSem.getSelectedItem()==null){
            JOptionPane.showMessageDialog(null,"Select semester","Professor", JOptionPane.ERROR_MESSAGE);
                return false;
        }
        else if(listSubject.getSelectedIndex()==-1){
            JOptionPane.showMessageDialog(null,"Select subject","Professor", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        return true;
        
    }
    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
    if(checkFields()){
        if(lblCheck.getText().equals("y")){

               
                if(professorDatabase.insert(txtProffesorName.getText(),listSubject.getSelectedValuesList(),(String)jcbCourseName.getSelectedItem(),Integer.parseInt((String)jcbSem.getSelectedItem()))){
                    
                    JOptionPane.showMessageDialog(null, "Record inserted","LoginSuccessed",JOptionPane.INFORMATION_MESSAGE);
                    dashboardPanel=DashBoardMain.getDashboardPanel();
                    dashboardPanel.addProfessorInJCBProf();
                    CustomJTable.insertInJtable(jtbProfessor,"professor");
                    
                }
          //  }
        }
        else
          JOptionPane.showMessageDialog(null, "Please insert proper Professor name","Professor",JOptionPane.WARNING_MESSAGE);
      
    }//GEN-LAST:event_btnAddActionPerformed
    }
    /**/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JComboBox<String> jcbCourseName;
    private javax.swing.JComboBox<String> jcbSem;
    private javax.swing.JTable jtbProfessor;
    private javax.swing.JLabel lblCheck;
    private javax.swing.JLabel lblCourseName;
    private javax.swing.JLabel lblProffesorName;
    private javax.swing.JLabel lblSem;
    private javax.swing.JLabel lblSubject;
    private javax.swing.JList<String> listSubject;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JTextField txtProffesorName;
    // End of variables declaration//GEN-END:variables
    private boolean cSelected=false,semSelected=false;
}
