
import database.SemesterDatabase;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author S Wadhwani
 */
public class Semester extends javax.swing.JPanel {

    /**
     * Creates new form Semester
     */
    SemesterDatabase semesterDatabase;
    public Semester() {
        initComponents();
       // int[] addYear = yearDatabase.getYears();
       semesterDatabase=new SemesterDatabase();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlYear = new javax.swing.JPanel();
        btnAddSem = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstYear = new javax.swing.JList<>();

        btnAddSem.setText("Add Sem");
        btnAddSem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddSemActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(lstYear);

        javax.swing.GroupLayout pnlYearLayout = new javax.swing.GroupLayout(pnlYear);
        pnlYear.setLayout(pnlYearLayout);
        pnlYearLayout.setHorizontalGroup(
            pnlYearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlYearLayout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addGroup(pnlYearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAddSem, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(116, 116, 116))
        );
        pnlYearLayout.setVerticalGroup(
            pnlYearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlYearLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(btnAddSem, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(pnlYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(pnlYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddSemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddSemActionPerformed
        
        if(semesterDatabase.insertSem())
            JOptionPane.showMessageDialog(null, "Record inserted","Course",JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnAddSemActionPerformed

    public SemesterDatabase getSemesterDatabase(){
        return semesterDatabase;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddSem;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> lstYear;
    private javax.swing.JPanel pnlYear;
    // End of variables declaration//GEN-END:variables
}
