
import java.sql.Date;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.JTable;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author rp wadhwani
 */
public class Tbl1 extends javax.swing.JPanel {

    /**
     * Creates new form Tbl1
     */
    public Tbl1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSendReport = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbDocuments = new javax.swing.JTable();

        btnSendReport.setText("Send Report");
        btnSendReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendReportActionPerformed(evt);
            }
        });

        jScrollPane1.setBackground(new java.awt.Color(26, 27, 65));
        jScrollPane1.setBorder(null);
        jScrollPane1.setForeground(new java.awt.Color(26, 27, 65));

        jtbDocuments.setBackground(new java.awt.Color(26, 27, 65));
        jtbDocuments.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jtbDocuments.setForeground(new java.awt.Color(247, 212, 136));
        jtbDocuments.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtbDocuments.setGridColor(new java.awt.Color(247, 212, 136));
        jtbDocuments.setRowHeight(22);
        jScrollPane1.setViewportView(jtbDocuments);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(287, 287, 287)
                .addComponent(btnSendReport)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 679, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(btnSendReport)
                .addGap(23, 23, 23))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSendReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendReportActionPerformed
        //issue in this,bcoz it is always getting a selected row in jtbdocuments
        int rows[]=jtbDocuments.getSelectedRows();
        if(rows.length!=0){
            String name=JOptionPane.showInputDialog(null,"Enter name of recipient","DashboardPanel", JOptionPane.INFORMATION_MESSAGE);
            String emailID=JOptionPane.showInputDialog(null,"Enter email id","DashboardPanel", JOptionPane.INFORMATION_MESSAGE);
            DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
            for(int i=0;i<rows.length;i++){
                String docName;
                docName=(String)jtbDocuments.getValueAt(rows[i],2);
                Date d=(Date)jtbDocuments.getValueAt(rows[i],3);
                String date=dateFormat.format(d);
                //System.out.println("d="+date);
                EmailExample.sendMail(name,docName,date,emailID,"Submitting","submitted");

            }

        }else{
            JOptionPane.showMessageDialog(null,"Please select row from submitted table", "dashboardpanel", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btnSendReportActionPerformed
    public JTable getTable(){
        return jtbDocuments;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSendReport;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtbDocuments;
    // End of variables declaration//GEN-END:variables
}
