
import java.sql.Date;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.JTable;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author rp wadhwani
 */
public class TblReIssue extends javax.swing.JPanel {

    /**
     * Creates new form TblReIssue
     */
    public TblReIssue() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jtblReIssue = new javax.swing.JTable();
        btnSendReport = new javax.swing.JButton();

        jScrollPane2.setBackground(new java.awt.Color(26, 27, 65));
        jScrollPane2.setForeground(new java.awt.Color(26, 27, 65));

        jtblReIssue.setBackground(new java.awt.Color(26, 27, 65));
        jtblReIssue.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jtblReIssue.setForeground(new java.awt.Color(247, 212, 136));
        jtblReIssue.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtblReIssue.setFocusable(false);
        jtblReIssue.setGridColor(new java.awt.Color(247, 212, 136));
        jtblReIssue.setRowHeight(22);
        jScrollPane2.setViewportView(jtblReIssue);

        btnSendReport.setText("Send Report");
        btnSendReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendReportActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(294, 294, 294)
                .addComponent(btnSendReport)
                .addContainerGap(292, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 659, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(266, Short.MAX_VALUE)
                .addComponent(btnSendReport)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(15, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(78, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSendReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendReportActionPerformed
        int rows[]=jtblReIssue.getSelectedRows();
        if(rows.length!=0){
            String name=JOptionPane.showInputDialog(null,"Enter name of recipient","DashboardPanel", JOptionPane.INFORMATION_MESSAGE);
            String emailID=JOptionPane.showInputDialog(null,"Enter email id","DashboardPanel", JOptionPane.INFORMATION_MESSAGE);
            DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
            for(int i=0;i<rows.length;i++){
                String docName;
                docName=(String)jtblReIssue.getValueAt(rows[i],0);
                Date d=(Date)jtblReIssue.getValueAt(rows[i],3);
                String date=dateFormat.format(d);
                //System.out.println("d="+date);
                EmailExample.sendMail(name,docName,date,emailID,"Re-issuing","re-issued");

            }

        }else{
            JOptionPane.showMessageDialog(null,"Please select row from submitted table", "dashboardpanel", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSendReportActionPerformed
    public JTable getTable(){
        return jtblReIssue;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSendReport;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jtblReIssue;
    // End of variables declaration//GEN-END:variables
}
